spring:
  profiles: local
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/crk5?serverTimezone=UTC&useSSL=false&autoReconnect=true&tinyInt1isBit=false&useUnicode=true&characterEncoding=utf8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    database: 0
    host: localhost
    port: 6379
    password:
  rabbitmq:
    host: localhost
    port: 5672
    username: yang
    password: 123456
server:
  port: 8080
logging:
  level:
    io:
      swagger:
        models:
          parameters:
            AbstractSerializableParameter: error
---
spring:
  profiles:
    active: local